model_name: "flux-dev"
data_config:
  train_batch_size: 1
  num_workers: 2
  img_size: 512
  img_dir: /home/user/imagesJSON/
  random_ratio: false # support multi crop preprocessing
report_to: wandb
train_batch_size: 1
output_dir: lora/
max_train_steps: 5000
learning_rate: 1e-3
lr_scheduler: linear
lr_warmup_steps: 100
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 0.01
adam_epsilon: 1e-8
max_grad_norm: 1.0
logging_dir: logs
mixed_precision: "bf16"
checkpointing_steps: 2000
saving_lora_steps: 500
checkpoints_total_limit: 2
tracker_project_name: mylora
resume_from_checkpoint: latest
gradient_accumulation_steps: 1
rank: 16
single_blocks: null
double_blocks: null
disable_sampling: false
sample_every: 250 # sample every this many steps
sample_width: 512
sample_height: 512
sample_steps: 20
sample_prompts:
    - "A photo of BT"
    - "BT eating a banana while riding a bike"
    - "BT fighting a demon on a volcano, Hell is in the background, The sky is dark, there's arftificial light."
